package org.jetbrains.exposed.sql.statements.jdbc

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import org.jetbrains.exposed.sql.statements.api.ResultApi
import org.jetbrains.exposed.sql.statements.api.RowApi
import java.sql.ResultSet

/**
 * Class for wrapping a [java.sql.ResultSet] generated by executing a statement that queries a JDBC database.
 *
 * @property result The actual [ResultSet] returned by the database after statement execution.
 */
class JdbcResult(
    val result: ResultSet
) : ResultApi, RowApi {

    override fun rows(): Flow<RowApi> = flow {
        while (next()) {
            emit(this@JdbcResult)
        }
    }

    override fun toString(): String = "JdbcResult(resultSet = $result)"

    override fun getObject(index: Int): Any? = result.getObject(index)

    override fun <T> getObject(index: Int, type: Class<T>): T? = result.getObject(index, type)

    override fun getObject(name: String): Any? = result.getObject(name)

    override fun <T> getObject(name: String, type: Class<T>): T? = result.getObject(name, type)

    fun next(): Boolean = result.next()

    override fun close() {
        releaseResult()
    }

    fun releaseResult() {
        val statement = result.statement
        statement?.close()
    }
}
