<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>exposed-maven-plugin</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        {{#versions}}
        <kotlin.version>{{kotlinVersion}}</kotlin.version>
        <exposed.version>{{exposedVersion}}</exposed.version>
        {{/versions}}
        <h2.version>2.4.240</h2.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.exposed</groupId>
            <artifactId>exposed-core</artifactId>
            <version>${exposed.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.exposed</groupId>
            <artifactId>exposed-jdbc</artifactId>
            <version>${exposed.version}</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>

        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>17</jvmTarget>
                    <args>
                        <arg>-opt-in=kotlin.uuid.ExperimentalUuidApi</arg>
                    </args>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jetbrains.exposed.plugin</groupId>
                <artifactId>exposed-maven-plugin</artifactId>
                <version>${exposed.version}</version>
                <configuration>
                    {{#exposedMigrations}}
                    {{#tablesPackage}}
                    <tablesPackage>{{tablesPackage}}</tablesPackage>
                    {{/tablesPackage}}

                    {{#fileDirectory}}
                    <fileDirectory>{{fileDirectory}}</fileDirectory>
                    {{/fileDirectory}}

                    {{#filePrefix}}
                    <filePrefix>{{filePrefix}}</filePrefix>
                    {{/filePrefix}}

                    {{#fileVersionFormat}}
                    <fileVersionFormat>{{fileVersionFormat}}</fileVersionFormat>
                    {{/fileVersionFormat}}

                    {{#fileSeparator}}
                    <fileSeparator>{{fileSeparator}}</fileSeparator>
                    {{/fileSeparator}}

                    {{#useUpperCaseDescription}}
                    <useUpperCaseDescription>{{useUpperCaseDescription}}</useUpperCaseDescription>
                    {{/useUpperCaseDescription}}

                    {{#fileExtension}}
                    <fileExtension>{{fileExtension}}</fileExtension>
                    {{/fileExtension}}

                    {{#fullFileName}}
                    <fullFileName>{{fullFileName}}</fullFileName>
                    {{/fullFileName}}

                    {{#databaseUrl}}
                    <databaseUrl>{{databaseUrl}}</databaseUrl>
                    {{/databaseUrl}}

                    {{#databaseUser}}
                    <databaseUser>{{databaseUser}}</databaseUser>
                    {{/databaseUser}}

                    {{#databasePassword}}
                    <databasePassword>{{databasePassword}}</databasePassword>
                    {{/databasePassword}}

                    {{#testContainersImage}}
                    <testContainersImage>{{testContainersImage}}</testContainersImage>
                    {{/testContainersImage}}

                    {{/exposedMigrations}}
                    <debug>true</debug>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
