package org.jetbrains.exposed.sql.statements.api

import java.sql.ResultSet

/** Base class for wrapping data generated by executing a statement that queries the database. */
interface ResultApi {
    /** The actual data object returned by the database after statement execution. */
    val result: Any

    /**
     * Returns the value of the column, at the specified [index], from the [result] object.
     * using the database's default type mapping.
     */
    fun getObject(index: Int): Any?

    /**
     * Returns the value of the column, at the specified [index], from the [result] object,
     * converted from the column SQL type to the specified data [type].
     */
    fun <T> getObject(index: Int, type: Class<T>): T?
}

/** Class for wrapping a [java.sql.ResultSet] generated by executing a statement that queries a JDBC database. */
class JdbcResult(
    /** The actual [ResultSet] returned by the database after statement execution. */
    override val result: ResultSet
) : ResultApi {
    override fun getObject(index: Int): Any? = result.getObject(index)

    override fun <T> getObject(index: Int, type: Class<T>): T? = result.getObject(index, type)
}
