/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.8/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

rootProject.name = "snippets"
include("exposed-dao")
include("exposed-dao-relationships")
include("exposed-dsl")
include("exposed-modules-maven")
include("exposed-modules-kotlin-gradle")
include("exposed-modules-groovy-gradle")
include("exposed-sql-functions")
