package org.jetbrains.exposed.v1.r2dbc.sql.statements.api

import org.jetbrains.exposed.v1.core.statements.StatementResult
import org.jetbrains.exposed.v1.core.statements.api.PreparedStatementApi
import java.sql.ResultSet

interface R2dbcPreparedStatementApi : PreparedStatementApi {
    /** Set the number of result set rows that should be fetched when generated by an executed statement. */
    suspend fun setFetchSize(value: Int?)

    /** Set the number of seconds the R2DBC driver will wait for a statement to execute. */
    suspend fun setTimeout(value: Int?)

    /** Adds parameters to the statement's batch of SQL commands. */
    suspend fun addBatch()

    /**
     * Executes an SQL query stored in a [PreparedStatement].
     *
     * @return The [ResultSet] generated by the query.
     */
    suspend fun executeQuery(): R2dbcResult

    /**
     * Executes an SQL statement stored in a [PreparedStatement].
     *
     * @return The affected row count if the executed statement is a DML type;
     * otherwise, 0 if the statement returns nothing.
     */
    suspend fun executeUpdate(): Int

    /**
     * Executes multiple SQL statements stored in a single [PreparedStatement].
     *
     * @return A list of [StatementResult]s retrieved from the database, which may store either affected row counts
     * or [ResultSet]s. The order of elements is based on the order of the statements in the `PreparedStatement`.
     */
    suspend fun executeMultiple(): List<StatementResult>

    /** The [io.r2dbc.spi.Row] object generated by the executed statement, or `null` if none was retrieved. */
    suspend fun getResultRow(): R2dbcResult?

    /** Closes the statement, if still open, and releases any of its database and/or driver resources. */
    suspend fun closeIfPossible()

    /**
     * Executes batched SQL statements stored as a [PreparedStatement].
     *
     * @return A list of the affected row counts, with one element for each statement,
     * ordered based on the order in which statements were provided to the batch.
     */
    suspend fun executeBatch(): List<Int>

    /** Cancels the statement, if supported by the database. */
    suspend fun cancel()
}
