package org.jetbrains.exposed.v1.spring.boot4.r2dbc.autoconfigure

import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.test.runTest
import org.jetbrains.exposed.v1.core.ResultRow
import org.jetbrains.exposed.v1.core.vendors.H2Dialect
import org.jetbrains.exposed.v1.r2dbc.R2dbcDatabaseConfig
import org.jetbrains.exposed.v1.r2dbc.selectAll
import org.jetbrains.exposed.v1.spring.boot4.r2dbc.Application
import org.jetbrains.exposed.v1.spring.boot4.r2dbc.DatabaseInitializer
import org.jetbrains.exposed.v1.spring.boot4.r2dbc.runTestWithMockTransactional
import org.jetbrains.exposed.v1.spring.boot4.r2dbc.tables.TestTable
import org.jetbrains.exposed.v1.spring7.reactive.transaction.ExposedSpringTransactionAttributeSource
import org.jetbrains.exposed.v1.spring7.reactive.transaction.SpringReactiveTransactionManager
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertSame
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.fail
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.NoSuchBeanDefinitionException
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.beans.factory.getBean
import org.springframework.boot.autoconfigure.AutoConfigurations
import org.springframework.boot.r2dbc.autoconfigure.R2dbcTransactionManagerAutoConfiguration
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.context.TestConfiguration
import org.springframework.boot.test.context.runner.ApplicationContextRunner
import org.springframework.context.annotation.Bean
import org.springframework.scheduling.annotation.Async
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import org.springframework.transaction.interceptor.TransactionAttributeSource
import java.util.concurrent.CompletableFuture

@SpringBootTest(
    classes = [Application::class, ExposedReactiveAutoConfigurationTest.CustomDatabaseConfigConfiguration::class],
    properties = ["spring.r2dbc.url=r2dbc:h2:mem:///test", "spring.exposed.database-driver=h2"]
)
class ExposedReactiveAutoConfigurationTest {
    @Autowired(required = false)
    private var springTransactionManager: SpringReactiveTransactionManager? = null

    @Autowired(required = false)
    private var databaseInitializer: DatabaseInitializer? = null

    @Autowired
    private var databaseConfig: R2dbcDatabaseConfig? = null

    @Autowired
    private var transactionAttributeSource: TransactionAttributeSource? = null

    @Test
    fun `should initialize the database connection`() {
        assertNotNull(springTransactionManager)
    }

    @Test
    fun `should not create schema`() {
        assertNull(databaseInitializer)
    }

    @Test
    fun `database config can be overrode by custom one`() {
        val expectedConfig = CustomDatabaseConfigConfiguration.expectedConfig
        assertSame(databaseConfig, expectedConfig)
        assertEquals(
            expectedConfig.maxEntitiesToStoreInCachePerEntity,
            databaseConfig!!.maxEntitiesToStoreInCachePerEntity
        )
    }

    @Test
    fun testClassExcludedFromAutoConfig() {
        val contextRunner = ApplicationContextRunner()
            .withConfiguration(AutoConfigurations.of(Application::class.java))
            .withPropertyValues("spring.exposed.database-driver=h2")
        contextRunner.run { context ->
            assertThrows(NoSuchBeanDefinitionException::class.java) {
                context.getBean<R2dbcTransactionManagerAutoConfiguration>()
            }
        }
    }

    @Test
    fun `load ExposedSpringTransactionAttributeSource`() {
        transactionAttributeSource?.let {
            assertEquals(ExposedSpringTransactionAttributeSource::class.java, it.javaClass)
        } ?: fail("TransactionAttributeSource bean not found")
    }

    @TestConfiguration
    open class CustomDatabaseConfigConfiguration {

        @Bean
        open fun customDatabaseConfig(): R2dbcDatabaseConfig {
            return expectedConfig
        }

        companion object {
            val expectedConfig = R2dbcDatabaseConfig {
                maxEntitiesToStoreInCachePerEntity = 777
                explicitDialect = H2Dialect()
            }.build()
        }
    }
}

@SpringBootTest(
    classes = [Application::class],
    properties = [
        "spring.r2dbc.url=r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;",
        "spring.exposed.generate-ddl=true",
        "spring.exposed.show-sql=true",
        "spring.exposed.database-driver=h2",
    ]
)
open class ExposedAutoConfigurationTestAutoGenerateDDL {

    @Autowired(required = false)
    private var springTransactionManager: SpringReactiveTransactionManager? = null

    @Autowired
    private lateinit var asyncService: AsyncExposedService

    @Test
    fun `should initialize the database connection`() = runTest {
        assertNotNull(springTransactionManager)
    }

    @Test
//    @Transactional // see [runTestWithMockTransactional]
    open fun `should create schema`() = runTestWithMockTransactional(springTransactionManager) {
        assertEquals(0L, TestTable.selectAll().count())
    }

    @Test
    @Transactional
    @Disabled // these are currently left disabled as they have always been disabled in both JDBC starters (see comments below)
    open fun `async service should be initialized properly`() = runTest {
        assertEquals(0, asyncService.allTestData().size)
    }

    @Test
    @Transactional
    @Disabled // these are currently left disabled as they have always been disabled in both JDBC starters (see comments below)
    open fun `async service should be initialized properly with completableFuture`() = runTest {
        assertEquals(0, asyncService.allTestDataAsync().join().size)
    }
}

// See https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#scheduling-annotation-support
@Transactional
@Service
@Async // if not put then allTestData() has no error. In all cases allTestDataAsync will have error
// Issue comes from TransactionAspectSupport, implementation changed between spring version 5.1.X and 5.2.0
open class AsyncExposedService {

    // if not using @EnableAsync, this method passes the test which should not
    open suspend fun allTestData() = TestTable.selectAll().toList()

    // you need to put open otherwise @Transactional is not applied since spring plugin not applied (similar to maven kotlin plugin)
    open suspend fun allTestDataAsync(): CompletableFuture<List<ResultRow>> = CompletableFuture.completedFuture(
        TestTable.selectAll().toList()
    )
}
