package org.jetbrains.exposed.sql.statements

import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.vendors.currentDialect
import java.sql.PreparedStatement
import java.util.*


class BatchInsertStatement(val table: Table, val _ignore: Boolean = false): Statement<List<Map<Column<*>, Any>>>(StatementType.INSERT, listOf(table)) {

    val data = ArrayList<LinkedHashMap<Column<*>, Any?>>()

    fun addBatch() {
        data.add(LinkedHashMap())
        arguments = null
    }

    operator fun <T> set(column: Column<T>, value: T) {
        val values = data.last()

        if (values.containsKey(column)) {
            error("$column is already initialized")
        }

        values.put(column, column.columnType.valueToDB(value))
    }

    private var arguments: List<List<Pair<Column<*>, Any?>>>? = null
        get() {
            return field ?: listOf(data.flatMap { single ->
                table.columns.filterNot { it.columnType.autoinc }.map {
                    it to (single[it] ?: it.defaultValueFun?.invoke() ?: it.dbDefaultValue?.let { DefaultValueMarker })
                }
            }).apply { field = this }
        }

    override fun arguments(): Iterable<Iterable<Pair<ColumnType, Any?>>> = arguments!!.map { it.map { it.first.columnType to it.second }.filter { it.second != DefaultValueMarker} }

    override fun prepareSQL(transaction: Transaction): String {
        if (data.isNotEmpty()) {
            val columns = table.columns.filterNot { it.columnType.autoinc }

            val values = buildString {
                append("VALUES ")

                val args = arguments!!.singleOrNull().orEmpty()
                val firstCol = columns.first()
                val lastCol = columns.last()
                val lastIndex = args.count() - 1
                args.forEachIndexed { i, it ->
                    if (it.first == firstCol)
                        append('(')
                    if (it.second != DefaultValueMarker)
                        append('?')
                    else {
                        if (transaction.db.supportsAlterTableWithAddColumn)
                            append("DEFAULT")
                        else
                            append(it.first.dbDefaultValue!!.toSQL(QueryBuilder(false)))
                    }

                    if (it.first == lastCol) {
                        append(')')
                        if (i < lastIndex) append(',')
                    } else
                        append(',')
                }
            }

            return transaction.db.dialect.insert(_ignore, table, columns, values, transaction)
        }

        error("No data provided to insert")
    }

    override fun PreparedStatement.executeInternal(transaction: Transaction): List<Map<Column<*>, Any>> {
        if (data.isEmpty()) return emptyList()

        val count = executeUpdate()

        assert(_ignore || count == data.size) { "Number of results don't match number of entries in batch" }

        val autoGeneratedKeys = arrayListOf<MutableMap<Column<*>, Any>>()

        val firstAutoIncColumn = table.columns.firstOrNull { it.columnType.autoinc }
        if (firstAutoIncColumn != null) {
            val rs = generatedKeys!!
            while (rs.next()) {
                autoGeneratedKeys.add(hashMapOf(firstAutoIncColumn to rs.getObject(1)))
            }

            if (count > 1 && !currentDialect.supportsMultipleGeneratedKeys) {
                // H2/SQLite only returns one last generated key...
                (autoGeneratedKeys[0][firstAutoIncColumn] as? Number)?.toLong()?.let {
                    var id = it

                    while (autoGeneratedKeys.size < count) {
                        id -= 1
                        autoGeneratedKeys.add(0, hashMapOf(firstAutoIncColumn to id))
                    }
                }
            }

            assert(_ignore || autoGeneratedKeys.isEmpty() || autoGeneratedKeys.size == count) {
                "Number of autoincs (${autoGeneratedKeys.size}) doesn't match number of batch entries ($count)"
            }
        }
        arguments!!.single().forEachIndexed { i, pair ->
            val itemIndx = i / table.columns.size
            val (col, value) = pair
            if (!col.columnType.autoinc) {
                val map = autoGeneratedKeys.getOrElse(itemIndx) {
                    hashMapOf<Column<*>, Any>().apply {
                        autoGeneratedKeys.add(itemIndx, this)
                    }
                }
                if (col.defaultValueFun != null && value != null && data[itemIndx][col] == null) {
                    map[col] = value
                }
            }
        }
        return autoGeneratedKeys
    }

}
