package org.jetbrains.exposed.v1.core.vendors

import org.jetbrains.exposed.v1.core.*
import org.jetbrains.exposed.v1.core.statements.MergeStatement
import org.jetbrains.exposed.v1.core.transactions.currentTransaction
import org.jetbrains.exposed.v1.exceptions.UnsupportedByDialectException
import org.jetbrains.exposed.v1.exceptions.throwUnsupportedException
import java.util.UUID as JavaUUID

private const val REDSHIFT_MAX_VARBYTE_LENGTH = 16_777_216

internal object RedshiftDataTypeProvider : DataTypeProvider() {
    override fun byteType(): String = "SMALLINT"
    override fun floatType(): String = "REAL"
    override fun integerAutoincType(): String = "INTEGER GENERATED BY DEFAULT AS IDENTITY(1, 1)"
    override fun uintegerAutoincType(): String = "BIGINT GENERATED BY DEFAULT AS IDENTITY(1, 1)"
    override fun longAutoincType(): String = "BIGINT GENERATED BY DEFAULT AS IDENTITY(1, 1)"

    override fun ulongAutoincType(): String {
        throw UnsupportedByDialectException(
            "Amazon Redshift identity columns must use INTEGER or BIGINT",
            currentDialect
        )
    }

    override fun textType(): String = "VARCHAR(MAX)"
    override fun mediumTextType(): String = textType()
    override fun largeTextType(): String = textType()

    override fun binaryType(): String = "VARBYTE($REDSHIFT_MAX_VARBYTE_LENGTH)"

    override fun binaryType(length: Int): String {
        if (length == Int.MAX_VALUE) return binaryType()
        require(length in 1..REDSHIFT_MAX_VARBYTE_LENGTH) {
            "Amazon Redshift VARBYTE length must be between 1 and $REDSHIFT_MAX_VARBYTE_LENGTH"
        }
        return "VARBYTE($length)"
    }

    override fun blobType(): String = binaryType()
    override fun uuidType(): String = "VARCHAR(36)"
    override fun uuidToDB(value: JavaUUID): Any = value.toString()
    override fun dateTimeType(): String = "TIMESTAMP"

    override fun jsonType(): String {
        throw UnsupportedByDialectException("Amazon Redshift does not support the JSON data type", currentDialect)
    }

    override fun vectorType(): String {
        throw UnsupportedByDialectException("Amazon Redshift does not support the VECTOR data type", currentDialect)
    }

    override fun hexToDb(hexString: String): String = "FROM_HEX('$hexString')"
}

@OptIn(InternalApi::class)
internal object RedshiftFunctionProvider : FunctionProvider() {
    override fun nextVal(seq: Sequence, builder: QueryBuilder) {
        currentTransaction().throwUnsupportedException("Amazon Redshift does not support sequences")
    }

    override fun random(seed: Int?): String = "RANDOM()"

    override fun concat(separator: String, queryBuilder: QueryBuilder, vararg expr: Expression<*>) {
        val escapedSeparator = separator.replace("'", "''")
        queryBuilder {
            expr.appendTo(separator = " || '$escapedSeparator' || ") { +it }
        }
    }

    override fun <T : String?> groupConcat(expr: GroupConcat<T>, queryBuilder: QueryBuilder) {
        queryBuilder {
            append("LISTAGG(")
            if (expr.distinct) append("DISTINCT ")
            append(expr.expr)
            expr.separator?.let { separator ->
                append(", '", separator.replace("'", "''"), "'")
            }
            append(")")
            if (expr.orderBy.isNotEmpty()) {
                expr.orderBy.appendTo(
                    prefix = " WITHIN GROUP (ORDER BY ",
                    postfix = ")"
                ) { (expression, sortOrder) ->
                    currentDialect.dataTypeProvider.precessOrderByClause(this, expression, sortOrder)
                }
            }
        }
    }

    override fun <T : String?> locate(queryBuilder: QueryBuilder, expr: Expression<T>, substring: String) {
        queryBuilder {
            append("POSITION('", substring.replace("'", "''"), "' IN ", expr, ")")
        }
    }

    override fun <T : String?> regexp(
        expr1: Expression<T>,
        pattern: Expression<String>,
        caseSensitive: Boolean,
        queryBuilder: QueryBuilder
    ) {
        if (!caseSensitive) {
            currentTransaction().throwUnsupportedException(
                "Amazon Redshift POSIX regular expressions support only case-sensitive matching"
            )
        }
        queryBuilder {
            append(expr1, " ~ ", pattern)
        }
    }

    override fun <T> date(expr: Expression<T>, queryBuilder: QueryBuilder) {
        queryBuilder { append("CAST(", expr, " AS DATE)") }
    }

    override fun <T> time(expr: Expression<T>, queryBuilder: QueryBuilder) {
        queryBuilder { append("CAST(", expr, " AS TIME)") }
    }

    override fun <T> year(expr: Expression<T>, queryBuilder: QueryBuilder) = extract("YEAR", expr, queryBuilder)
    override fun <T> month(expr: Expression<T>, queryBuilder: QueryBuilder) = extract("MONTH", expr, queryBuilder)
    override fun <T> day(expr: Expression<T>, queryBuilder: QueryBuilder) = extract("DAY", expr, queryBuilder)
    override fun <T> hour(expr: Expression<T>, queryBuilder: QueryBuilder) = extract("HOUR", expr, queryBuilder)
    override fun <T> minute(expr: Expression<T>, queryBuilder: QueryBuilder) = extract("MINUTE", expr, queryBuilder)
    override fun <T> second(expr: Expression<T>, queryBuilder: QueryBuilder) = extract("SECOND", expr, queryBuilder)

    private fun <T> extract(part: String, expr: Expression<T>, queryBuilder: QueryBuilder) {
        queryBuilder { append("EXTRACT($part FROM ", expr, ")") }
    }

    override fun update(
        target: Table,
        columnsAndValues: List<Pair<Column<*>, Any?>>,
        limit: Int?,
        where: Op<Boolean>?,
        transaction: Transaction
    ): String {
        if (limit != null) {
            transaction.throwUnsupportedException("Amazon Redshift does not support LIMIT in an UPDATE clause")
        }
        return super.update(target, columnsAndValues, null, where, transaction)
    }

    override fun delete(
        ignore: Boolean,
        table: Table,
        where: String?,
        limit: Int?,
        transaction: Transaction
    ): String {
        if (limit != null) {
            transaction.throwUnsupportedException("Amazon Redshift does not support LIMIT in a DELETE clause")
        }
        return super.delete(ignore, table, where, null, transaction)
    }

    override fun upsert(
        table: Table,
        data: List<Pair<Column<*>, Any?>>,
        expression: String,
        onUpdate: List<Pair<Column<*>, Any?>>,
        keyColumns: List<Column<*>>,
        where: Op<Boolean>?,
        transaction: Transaction
    ): String {
        if (where != null) {
            transaction.throwUnsupportedException("Amazon Redshift MERGE does not support a single WHERE clause")
        }
        if (keyColumns.isEmpty()) {
            transaction.throwUnsupportedException("UPSERT requires a unique key or constraint as a conflict target")
        }

        val dataColumns = data.unzip().first
        val autoIncColumn = table.autoIncColumn
        val dataColumnsWithoutAutoInc = autoIncColumn?.let { dataColumns - autoIncColumn } ?: dataColumns
        val onUpdateWithoutAutoInc = autoIncColumn?.let { autoInc ->
            onUpdate.filterNot { (column, _) -> column == autoInc }
        } ?: onUpdate
        if (!dataColumns.containsAll(keyColumns)) {
            transaction.throwUnsupportedException("Amazon Redshift UPSERT requires values for all key columns")
        }
        return with(QueryBuilder(true)) {
            +"MERGE INTO "
            table.describe(transaction, this)
            // Redshift MERGE requires a relation-backed source and concrete types for prepared parameters.
            +" USING (SELECT "
            data.appendTo(this) { (column, value) ->
                append("CAST(")
                registerArgument(column, value)
                append(" AS ", column.columnType.rawSqlType().sqlType(), ") AS ", transaction.identity(column))
            }
            +" FROM pg_catalog.pg_class LIMIT 1) AS S ON ("
            keyColumns.appendTo(this, separator = " AND ") { column ->
                append(transaction.fullIdentity(column), "=S.", transaction.identity(column))
            }
            +")"

            if (onUpdateWithoutAutoInc.isNotEmpty()) {
                +" WHEN MATCHED THEN UPDATE SET "
                onUpdateWithoutAutoInc.appendTo(this) { (column, updateExpression) ->
                    append(transaction.identity(column), "=")
                    registerArgument(column, updateExpression)
                }
            }

            +" WHEN NOT MATCHED THEN INSERT "
            dataColumnsWithoutAutoInc.appendTo(this, prefix = "(", postfix = ")") { column ->
                append(transaction.identity(column))
            }
            dataColumnsWithoutAutoInc.appendTo(this, prefix = " VALUES (", postfix = ")") { column ->
                append("S.", transaction.identity(column))
            }
            toString()
        }
    }

    override fun merge(
        dest: Table,
        source: Table,
        transaction: Transaction,
        clauses: List<MergeStatement.Clause>,
        on: Op<Boolean>?
    ): String {
        validateMergeClauses(transaction, clauses)
        return super.merge(dest, source, transaction, clauses, on)
    }

    override fun mergeSelect(
        dest: Table,
        source: QueryAlias,
        transaction: Transaction,
        clauses: List<MergeStatement.Clause>,
        on: Op<Boolean>,
        prepared: Boolean
    ): String {
        validateMergeClauses(transaction, clauses)
        return super.mergeSelect(dest, source, transaction, clauses, on, prepared)
    }

    private fun validateMergeClauses(transaction: Transaction, clauses: List<MergeStatement.Clause>) {
        when {
            clauses.count { it.type == MergeStatement.ClauseCondition.MATCHED } > 1 ->
                transaction.throwUnsupportedException("Amazon Redshift MERGE supports only one WHEN MATCHED clause")
            clauses.count { it.type == MergeStatement.ClauseCondition.NOT_MATCHED } > 1 ->
                transaction.throwUnsupportedException("Amazon Redshift MERGE supports only one WHEN NOT MATCHED clause")
            clauses.any { it.and != null } ->
                transaction.throwUnsupportedException("Amazon Redshift MERGE does not support additional WHEN conditions")
        }
    }

    override fun explain(
        analyze: Boolean,
        options: String?,
        internalStatement: String,
        transaction: Transaction
    ): String {
        if (analyze) {
            transaction.throwUnsupportedException("Amazon Redshift does not support ANALYZE in EXPLAIN queries")
        }
        if (options != null && !options.equals("VERBOSE", ignoreCase = true)) {
            transaction.throwUnsupportedException("Amazon Redshift supports only the VERBOSE option in EXPLAIN queries")
        }
        return super.explain(false, options, internalStatement, transaction)
    }
}

/**
 * Amazon Redshift dialect implementation for JDBC.
 *
 * Amazon Redshift does not return generated identity values as part of an insert operation. Use explicit IDs or
 * client-generated IDs when the inserted ID is required by the application.
 * Amazon Redshift does not recognize CHECK constraint syntax, so byte, unsigned byte, and unsigned short columns are
 * not protected by range enforcement.
 * Text columns map to `VARCHAR(MAX)`, whose maximum size is 65,535 bytes.
 * Binary columns map to `VARBYTE(16777216)`.
 * UUID columns use the standard dashed string format for writes and accept dashed or undashed hexadecimal text on reads.
 */
@OptIn(InternalApi::class)
open class RedshiftDialect : VendorDialect(dialectName, RedshiftDataTypeProvider, RedshiftFunctionProvider) {
    override val supportsCreateSequence: Boolean = false
    override val defaultReferenceOption: ReferenceOption = ReferenceOption.NO_ACTION
    override val supportsMultipleGeneratedKeys: Boolean = false
    override val supportsGeneratedKeysRetrieval: Boolean = false
    override val supportsOnlyIdentifiersInGeneratedKeys: Boolean = true
    override val supportsSubqueryUnions: Boolean = true
    override val supportsOrderByNullsFirstLast: Boolean = true
    override val supportsOnUpdate: Boolean = false
    override val supportsOnDelete: Boolean = false
    override val supportsSetDefaultReferenceOption: Boolean = false
    override val supportsRestrictReferenceOption: Boolean = false
    override val requiresAutoCommitOnCreateDrop: Boolean = true
    override val supportsAlterCheckConstraint: Boolean = false
    override val supportsCheckConstraints: Boolean = false

    override fun createIndex(index: Index): String {
        if (!index.unique || index.filterCondition != null || !index.functions.isNullOrEmpty() || index.indexType != null) {
            exposedLogger.warn(
                "Index ${index.indexName} on ${index.table.tableName} is not supported by Amazon Redshift and will not be created."
            )
            return ""
        }
        return super.createIndex(index)
    }

    override fun dropIndex(
        tableName: String,
        indexName: String,
        isUnique: Boolean,
        isPartialOrFunctional: Boolean
    ): String {
        if (!isUnique || isPartialOrFunctional) {
            exposedLogger.warn(
                "Index $indexName on $tableName is not supported by Amazon Redshift and will not be dropped."
            )
            return ""
        }
        return super.dropIndex(tableName, indexName, isUnique, isPartialOrFunctional)
    }

    override fun modifyColumn(column: Column<*>, columnDiff: ColumnDiff): List<String> {
        currentTransaction().throwUnsupportedException(
            "Column modification is not supported by the Amazon Redshift dialect"
        )
    }

    override fun createDatabase(name: String): String {
        @OptIn(InternalApi::class)
        return "CREATE DATABASE ${name.inProperCase()}"
    }

    override fun listDatabases(): String = "SELECT datname FROM pg_database"

    override fun dropDatabase(name: String): String {
        @OptIn(InternalApi::class)
        return "DROP DATABASE ${name.inProperCase()}"
    }

    override fun setSchema(schema: Schema): String = "SET search_path TO ${schema.identifier}"

    override fun setColumnComment(column: Column<*>, comment: String?): List<String> {
        @OptIn(InternalApi::class)
        val fullColumnIdentity = currentTransaction().fullIdentity(column)
        return listOf(
            if (comment != null) {
                "COMMENT ON COLUMN $fullColumnIdentity IS '${comment.escapeComment()}'"
            } else {
                "COMMENT ON COLUMN $fullColumnIdentity IS NULL"
            }
        )
    }

    companion object : DialectNameProvider("Redshift")
}
