package org.jetbrains.exposed.v1.tests.redshift

import nl.altindag.log.LogCaptor
import org.jetbrains.exposed.v1.core.*
import org.jetbrains.exposed.v1.core.java.javaUUID
import org.jetbrains.exposed.v1.core.statements.buildStatement
import org.jetbrains.exposed.v1.core.vendors.RedshiftDialect
import org.jetbrains.exposed.v1.core.vendors.currentDialect
import org.jetbrains.exposed.v1.exceptions.UnsupportedByDialectException
import org.jetbrains.exposed.v1.jdbc.Database
import org.jetbrains.exposed.v1.jdbc.JdbcTransaction
import org.jetbrains.exposed.v1.jdbc.SchemaUtils
import org.jetbrains.exposed.v1.jdbc.exists
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.statements.InsertBlockingExecutable
import org.jetbrains.exposed.v1.jdbc.statements.jdbc.JdbcPreparedStatementImpl
import org.jetbrains.exposed.v1.jdbc.transactions.TransactionManager
import org.jetbrains.exposed.v1.jdbc.transactions.transaction
import org.jetbrains.exposed.v1.tests.TestDB
import org.junit.jupiter.api.Assumptions
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.util.UUID
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertTrue

class RedshiftTests {
    @BeforeEach
    fun requireH2() {
        Assumptions.assumeTrue(TestDB.H2_V2 in TestDB.enabledDialects())
    }

    @Test
    fun testRedshiftDataTypesAndIdentityDdl() {
        val table = object : Table("redshift_types") {
            val id = long("id").autoIncrement()
            val externalId = uuid("external_id")
            val javaExternalId = javaUUID("java_external_id")
            val description = text("description")
            val payload = binary("payload", 128)
            val unboundedPayload = binary("unbounded_payload", Int.MAX_VALUE)
            val attachment = blob("attachment")
            val quantity = integer("quantity")

            override val primaryKey = PrimaryKey(id)
        }

        withRedshiftDialect {
            assertEquals("BIGINT GENERATED BY DEFAULT AS IDENTITY(1, 1)", table.id.columnType.sqlType())
            assertEquals("VARCHAR(36)", table.externalId.columnType.sqlType())
            assertEquals("VARCHAR(36)", table.javaExternalId.columnType.sqlType())
            assertEquals("VARCHAR(MAX)", table.description.columnType.sqlType())
            assertEquals("VARBYTE(128)", table.payload.columnType.sqlType())
            assertEquals("VARBYTE(16777216)", table.unboundedPayload.columnType.sqlType())
            assertEquals("VARBYTE(16777216)", table.attachment.columnType.sqlType())

            val createTable = table.ddl.single()
            assertContains(createTable, "GENERATED BY DEFAULT AS IDENTITY(1, 1)")
            assertFalse(createTable.contains("CHECK"))
            assertFalse(currentDialect.supportsGeneratedKeysRetrieval)
            assertFalse(currentDialect.supportsCreateSequence)
            val undashedUuid = "00112233445566778899aabbccddeeff"
            val dashedUuid = "00112233-4455-6677-8899-aabbccddeeff"
            assertEquals(kotlin.uuid.Uuid.parseHex(undashedUuid), table.externalId.columnType.valueFromDB(undashedUuid))
            assertEquals(UUID.fromString(dashedUuid), table.javaExternalId.columnType.valueFromDB(undashedUuid))
            assertFailsWith<IllegalStateException> {
                table.externalId.columnType.valueFromDB("not-a-uuid")
            }
            assertFailsWith<IllegalStateException> {
                table.javaExternalId.columnType.valueFromDB("not-a-uuid")
            }
        }
    }

    @Test
    fun testCheckConstraintWarningsUseEffectiveConstraintsAndNameTable() {
        val tableWithoutEffectiveChecks = object : Table("redshift_without_effective_checks") {
            val value = integer("value")
        }
        val tableWithRangeChecks = object : Table("redshift_with_range_checks") {
            val signedByte = byte("signed_byte")
            val unsignedByte = ubyte("unsigned_byte")
            val unsignedShort = ushort("unsigned_short")
        }
        val tableWithCheck = object : Table("redshift_with_check") {
            val value = integer("value").check("positive_value") { it greater 0 }
        }

        withRedshiftDialect {
            val logCaptor = LogCaptor.forName(exposedLogger.name)
            try {
                tableWithoutEffectiveChecks.ddl
                assertTrue(logCaptor.warnLogs.isEmpty())

                assertFalse(tableWithRangeChecks.ddl.single().contains(" CHECK "))
                assertContains(logCaptor.warnLogs.single(), identity(tableWithRangeChecks))
                logCaptor.clearLogs()

                tableWithCheck.ddl
                val warning = logCaptor.warnLogs.single()
                assertContains(warning, identity(tableWithCheck))
                assertContains(warning, RedshiftDialect.dialectName)
            } finally {
                logCaptor.clearLogs()
                logCaptor.close()
            }
        }
    }

    @Test
    fun testForeignKeyActionsAndChecksAreOmitted() {
        val parent = object : Table("redshift_parent") {
            val id = integer("id")
            override val primaryKey = PrimaryKey(id)
        }
        val child = object : Table("redshift_child") {
            val parentId = integer("parent_id").references(
                parent.id,
                onDelete = ReferenceOption.CASCADE,
                onUpdate = ReferenceOption.CASCADE
            )
        }

        withRedshiftDialect {
            val createTable = child.ddl.single()
            assertContains(createTable, "FOREIGN KEY")
            assertFalse(createTable.contains("ON DELETE"))
            assertFalse(createTable.contains("ON UPDATE"))
            assertFalse(createTable.contains("CHECK"))
        }
    }

    @Test
    fun testUnsupportedIndexesAreSkippedAndUniqueConstraintsAreCreated() {
        val table = object : Table("redshift_indices") {
            val code = varchar("code", 32).index()
        }

        withRedshiftDialect {
            val logCaptor = LogCaptor.forName(exposedLogger.name)
            try {
                val createStatements = SchemaUtils.createStatements(table)
                assertTrue(createStatements.all { it.isNotBlank() })
                assertEquals(1, createStatements.size)
                logCaptor.clearLogs()

                SchemaUtils.create(table, inBatch = true)
                assertTrue(table.exists())

                val warning = logCaptor.warnLogs.single()
                assertContains(warning, table.tableName)
                assertContains(warning, "will not be created")
                assertTrue(table.indices.single().createStatement().isEmpty())
                assertTrue(table.indices.single().dropStatement().isEmpty())

                val uniqueConstraint = Index(
                    columns = listOf(table.code),
                    unique = true,
                    customName = "uq_redshift_indices_code"
                ).createStatement().single()
                assertContains(uniqueConstraint, "ADD CONSTRAINT")
                assertContains(uniqueConstraint, "UNIQUE")
            } finally {
                SchemaUtils.drop(table)
                logCaptor.clearLogs()
                logCaptor.close()
            }
        }
    }

    @Test
    fun testUnsupportedColumnModificationFailsFast() {
        val table = object : Table("redshift_column_modification") {
            val value = varchar("value", 32)
        }

        withRedshiftDialect {
            val exception = assertFailsWith<UnsupportedByDialectException> {
                table.value.modifyStatements(ColumnDiff.AllChanged)
            }
            assertContains(exception.message.orEmpty(), "Column modification")
        }
    }

    @Test
    fun testRedshiftSpecificFunctionSql() {
        val table = object : Table("redshift_functions") {
            val name = varchar("name", 32)
            val flags = integer("flags")
        }

        withRedshiftDialect {
            assertEquals("RANDOM()", Random(seed = 42).toString())
            assertEquals(
                "'one' || '-' || 'two' || '-' || 'three'",
                concat("-", listOf(stringLiteral("one"), stringLiteral("two"), stringLiteral("three"))).toString()
            )
            assertEquals(
                "'one' || '''' || 'two'",
                concat("'", listOf(stringLiteral("one"), stringLiteral("two"))).toString()
            )

            val name = fullIdentity(table.name)
            assertEquals("$name ~ '^[A-Z]'", table.name.regexp(stringLiteral("^[A-Z]")).toString())
            assertFailsWith<UnsupportedByDialectException> {
                table.name.regexp(stringLiteral("^[a-z]"), caseSensitive = false).toString()
            }

            val flags = fullIdentity(table.flags)
            assertEquals("($flags+7-($flags & 7))", (table.flags bitwiseOr 7).toString())
            assertEquals("(($flags+7-($flags & 7))-($flags & 7))", (table.flags bitwiseXor 7).toString())
        }
    }

    @Test
    fun testExplainSupportsOnlyRedshiftSyntax() {
        withRedshiftDialect {
            val functionProvider = currentDialect.functionProvider
            assertEquals("EXPLAIN SELECT 1", functionProvider.explain(false, null, "SELECT 1", this))
            assertEquals("EXPLAIN VERBOSE SELECT 1", functionProvider.explain(false, "VERBOSE", "SELECT 1", this))
            assertFailsWith<UnsupportedByDialectException> {
                functionProvider.explain(true, null, "SELECT 1", this)
            }
            assertFailsWith<UnsupportedByDialectException> {
                functionProvider.explain(false, "FORMAT JSON", "SELECT 1", this)
            }
        }
    }

    @Test
    fun testUpsertUsesTypedRedshiftMergeSourceQuery() {
        val table = object : Table("redshift_upsert") {
            val code = varchar("code", 32)
            val value = integer("value")
            val payload = binary("payload", 128)

            override val primaryKey = PrimaryKey(code)
        }

        withRedshiftDialect {
            val statement = buildStatement {
                table.upsert(table.code) {
                    it[code] = "A"
                    it[value] = 1
                    it[payload] = byteArrayOf(1, 2, 3)
                }
            }
            val codeName = identity(table.code)
            val valueName = identity(table.value)
            val payloadName = identity(table.payload)
            val expected = buildString {
                append("MERGE INTO ${identity(table)} ")
                append(
                    "USING (SELECT CAST(? AS VARCHAR(32)) AS $codeName, " +
                        "CAST(? AS INT) AS $valueName, CAST(? AS VARBYTE(128)) AS $payloadName " +
                        "FROM pg_catalog.pg_class LIMIT 1) AS S "
                )
                append("ON (${fullIdentity(table.code)}=S.$codeName) ")
                append("WHEN MATCHED THEN UPDATE SET $valueName=S.$valueName, $payloadName=S.$payloadName ")
                append("WHEN NOT MATCHED THEN INSERT ($codeName, $valueName, $payloadName) ")
                append("VALUES (S.$codeName, S.$valueName, S.$payloadName)")
            }

            assertEquals(expected, statement.prepareSQL(this, prepared = true))
            assertFalse(statement.prepareSQL(this, prepared = true).contains("(VALUES"))
        }
    }

    @Test
    fun testUpsertOmitsIdentityColumnFromInsertClause() {
        val table = object : Table("redshift_upsert_identity") {
            val id = integer("id").autoIncrement()
            val code = varchar("code", 32)
            val value = integer("value")

            override val primaryKey = PrimaryKey(code)
        }

        withRedshiftDialect {
            val statement = buildStatement {
                table.upsert(table.code) {
                    it[id] = 99
                    it[code] = "A"
                    it[value] = 1
                }
            }
            val sql = statement.prepareSQL(this, prepared = true)
            val updateClause = sql.substringAfter("WHEN MATCHED THEN UPDATE SET ").substringBefore(" WHEN NOT MATCHED")
            val insertClause = sql.substringAfter("WHEN NOT MATCHED THEN INSERT ")

            assertContains(sql.substringBefore("WHEN NOT MATCHED"), "CAST(? AS INT) AS ${identity(table.id)}")
            assertFalse(updateClause.contains("${identity(table.id)}="))
            assertFalse(insertClause.substringBefore(" VALUES ").contains(identity(table.id)))
            assertEquals(
                "(${identity(table.code)}, ${identity(table.value)}) " +
                    "VALUES (S.${identity(table.code)}, S.${identity(table.value)})",
                insertClause
            )
        }
    }

    @Test
    fun testUnsupportedReturningAndDmlLimitsFailBeforeExecution() {
        val table = object : Table("redshift_dml") {
            val id = integer("id")
            val value = varchar("value", 32)

            override val primaryKey = PrimaryKey(id)
        }

        withRedshiftDialect {
            val returning = buildStatement {
                table.insertReturning {
                    it[id] = 1
                    it[value] = "A"
                }
            }
            assertFailsWith<UnsupportedByDialectException> {
                returning.prepareSQL(this, prepared = true)
            }

            val update = buildStatement {
                table.update(limit = 1) {
                    it[value] = "B"
                }
            }
            assertFailsWith<UnsupportedByDialectException> {
                update.prepareSQL(this, prepared = true)
            }

            val delete = buildStatement {
                table.deleteWhere(limit = 1) { id eq 1 }
            }
            assertFailsWith<UnsupportedByDialectException> {
                delete.prepareSQL(this, prepared = true)
            }
        }
    }

    @Test
    fun testUnsupportedArrayTypeFailsBeforeExecution() {
        val table = object : Table("redshift_arrays") {
            val values = array<Int>("values")
        }

        withRedshiftDialect {
            assertFailsWith<UnsupportedByDialectException> {
                table.values.columnType.sqlType()
            }
        }
    }

    @Test
    fun testInsertDoesNotRequestGeneratedKeys() {
        val table = object : Table("redshift_generated_keys") {
            val id = integer("id").autoIncrement()
            val payload = varchar("payload", 32)
        }

        withRedshiftDialect {
            try {
                exec("CREATE TABLE redshift_generated_keys (id INTEGER NOT NULL, payload VARCHAR(32) NOT NULL)")
                val statement = buildStatement {
                    table.insert {
                        it[payload] = "A"
                    }
                }
                val prepared = InsertBlockingExecutable(statement).prepared(
                    this,
                    statement.prepareSQL(this, prepared = true)
                )

                try {
                    val jdbcPrepared = assertIs<JdbcPreparedStatementImpl>(prepared)
                    assertFalse(jdbcPrepared.wasGeneratedKeysRequested)
                } finally {
                    prepared.closeIfPossible()
                }
            } finally {
                exec("DROP TABLE IF EXISTS redshift_generated_keys")
            }
        }
    }

    @Test
    fun testReadingGeneratedIdReportsUnsupportedOperation() {
        val table = object : Table("redshift_generated_id") {
            val id = integer("id").autoIncrement()
            val payload = varchar("payload", 32)
        }

        withRedshiftDialect {
            try {
                exec(
                    "CREATE TABLE redshift_generated_id (" +
                        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload VARCHAR(32) NOT NULL)"
                )
                val insert = table.insert {
                    it[payload] = "A"
                }

                val exception = assertFailsWith<UnsupportedByDialectException> {
                    insert[table.id]
                }
                assertContains(exception.message.orEmpty(), "redshift_generated_id.id")
            } finally {
                exec("DROP TABLE IF EXISTS redshift_generated_id")
            }
        }
    }

    private fun withRedshiftDialect(statement: JdbcTransaction.() -> Unit) {
        val database = Database.connect(
            url = "jdbc:h2:mem:redshift-${UUID.randomUUID()}",
            driver = TestDB.H2_V2.driver,
            databaseConfig = DatabaseConfig { explicitDialect = RedshiftDialect() }
        )
        try {
            transaction(database) {
                maxAttempts = 1
                statement()
            }
        } finally {
            TransactionManager.closeAndUnregister(database)
        }
    }
}
