spring:
  application:
    name: springboot3-exposed-r2dbc
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/schedule_system
    username: root
    password: root
  sql:
    init:
      mode: never

  threads:
    virtual:
      enabled: true
logging:
  level:
    root: info
  pattern:
    console: "%yellow([%date{yyyy-MM-dd HH:mm:ss}]) %blue([%thread]) %green(%file:%line) %highlight(%-5level){FATAL=red, ERROR=bright-red, WARN=yellow, INFO=green, DEBUG=cyan, TRACE=blue} %cyan(%logger{36}) : %magenta(%msg%n)"
