package org.jetbrains.exposed.v1.core.statements.api

import kotlinx.coroutines.flow.Flow

/**
 * Base class for wrapping data generated by executing a statement that queries the database.
 */
interface ResultApi : AutoCloseable {
    /**
     * Returns a [Flow] containing the results of applying the given transform function [block] to each original row
     * of data generated by executing a statement.
     */
    fun <T> mapRows(block: (row: RowApi) -> T?): Flow<T?>
}

/**
 * Base representation of accessors to data rows, by index or column name.
 *
 * This API allows retrieving objects from a row, either by the one-based index of the column or by its name,
 * with optional type conversion for strongly-typed results.
 */
interface RowApi {
    /**
     * Gets the value of the column at the specified [index] position in the current data row.
     *
     * @param index The first column is at position one, the second at position two, and onwards.
     */
    fun getObject(index: Int): Any?

    /** Gets the value of the column with the specified [name] in the current data row. */
    fun getObject(name: String): Any?

    /**
     * Gets the value of the column at the specified [index] position in the current data row
     * and converts the stored SQL type to the requested [type], if the conversion is supported.
     *
     * @param index The first column is at position one, the second at position two, and onwards.
     */
    fun <T> getObject(index: Int, type: Class<T>): T?

    /**
     * Gets the value of the column with the specified [name] in the current data row and converts the stored SQL type
     * to the requested [type], if the conversion is supported.
     */
    fun <T> getObject(name: String, type: Class<T>): T?
}
