name: "CI"
on: [pull_request]
jobs:
  Detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "detekt"
        uses: alaegin/Detekt-Action@v1.22.0-RC3
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt.yml
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
      - name: Start Databases
        run: ./scripts/setup.sh
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          IS_RELEASE_BUILD: false
        with:
          gradle-version: 7.6
          arguments: clean test build artifactoryPublish
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Test Artifacts
          path: exposed-tests/build/test-results/*/*.xml

