name: "CI"
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Start Databases
        run: ./scripts/setup.sh
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          IS_RELEASE_BUILD: false
        with:
          gradle-version: 7.3
          arguments: clean test build artifactoryPublish
      - name: List Build Outputs
        run: cd exposed-tests/build/test-results/test && ls -lart
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: Test Artifacts
          path: exposed-tests/build/test-results/*/*.xml

