name: Deploy Dokka to GitHub Pages

# Published API reference docs to GitHub Pages automatically
# for every release. Can also be triggered manually
on:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build API reference
        run: ./gradlew dokkaHtmlMultiModule
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule
          desination_dir: api
          full_commit_message: Publish API reference documentation
